// Generated by CoffeeScript 1.10.0
(function() {
  var Rx, bot, incoming, log, messageTextToLowerCaseExceptTags, nullBack, outgoing, ref, self, send, slack, token, typeIs, userIsnt;

  slack = require('slack');

  Rx = require('rx');

  ref = require('../misc/helpers').slack, messageTextToLowerCaseExceptTags = ref.messageTextToLowerCaseExceptTags, typeIs = ref.typeIs, userIsnt = ref.userIsnt;

  log = require('../misc/util').log;

  nullBack = function(err, data) {};

  token = process.env.SLACK_TOKEN;

  self = 'U0WRAJMB5';

  bot = slack.rtm.client();

  bot.listen({
    token: token
  });

  bot.hello(function(message) {
    return slack.chat.postMessage({
      token: token,
      channel: 'D0WSS7VGQ',
      text: "Hi there. Looking for someone? Or perhaps you'd like to share your whereabouts?",
      as_user: true
    }, nullBack);
  });


  /* PUBLIC */

  incoming = {};

  incoming.event$ = Rx.Observable.create(function(observer) {
    return bot.message(function(data) {
      return observer.onNext(data);
    });
  });

  incoming.message$ = incoming.event$.where(typeIs('message')).where(userIsnt(self)).map(messageTextToLowerCaseExceptTags).share();

  outgoing = {};

  outgoing.message$ = new Rx.Subject();

  send = function(bundle) {
    var message, reply;
    message = bundle.message, reply = bundle.reply;
    return slack.chat.postMessage({
      token: token,
      channel: message.channel,
      text: reply,
      as_user: true
    }, nullBack);
  };

  module.exports = {
    incoming: incoming,
    outgoing: outgoing,
    send: send
  };

}).call(this);
