// Generated by CoffeeScript 1.10.0
(function() {
  var Rx, arrayNotEmpty, dot, getText, log, makeStateObject, outcome$, processMessage, token, wit;

  Rx = require('rx');

  wit = require('node-wit');

  log = require('../misc/util').log;

  dot = require('../misc/helpers').dot;


  /* PRIVATE */

  token = process.env.WIT_TOKEN;

  getText = dot('text');

  arrayNotEmpty = function(array) {
    return array.length > 0;
  };

  makeStateObject = function(state) {
    return {
      context: {
        state: state
      }
    };
  };


  /* PUBLIC */

  outcome$ = new Rx.Subject();

  processMessage = function(message, state) {
    return wit.captureTextIntent(token, getText(message), makeStateObject(state), (function(_this) {
      return function(err, res) {
        if (arrayNotEmpty(res.outcomes)) {
          return outcome$.onNext({
            message: message,
            outcome: res.outcomes[0]
          });
        }
      };
    })(this));
  };

  module.exports = {
    outcome$: outcome$.share(),
    processMessage: processMessage
  };

}).call(this);
