// Generated by CoffeeScript 1.10.0
(function() {
  var Firebase, R, defaultTo, exports, getBase, getChild, getSnapshot, getValue, getValueWithDefault, log, message, setValue, snapshotToValue;

  R = require('ramda');

  Firebase = require('firebase');

  log = require('../../misc/util').log;

  getBase = function(url) {
    return new Firebase(url);
  };

  getChild = R.curry(function(name, ref) {
    return ref.child(name);
  });

  getSnapshot = function(ref) {
    return ref.once('value');
  };

  snapshotToValue = function(snapshot) {
    return snapshot.val();
  };

  getValue = R.pipe(getSnapshot, snapshotToValue);

  defaultTo = R.curry(function(defaultValue, val) {
    if (val == null) {
      return defaultValue;
    } else {
      return val;
    }
  });

  getValueWithDefault = function(defaultValue) {
    return R.pipeP(getValue, defaultTo(defaultValue));
  };

  setValue = R.curry(function(value, ref) {
    return ref.set(value);
  });

  message = {
    user: 'U036HR7S2',
    team: 'T02FHSL18'
  };

  exports = {
    getBase: getBase,
    getValue: getValue,
    getValueWithDefault: getValueWithDefault,
    setValue: setValue
  };

}).call(this);
