// Generated by CoffeeScript 1.10.0
(function() {
  exports.intents = {
    'set_self_status': function(message, entities) {
      var reply;
      setUserStatus(message, entities);
      reply = [replies.intents.set_self_status];
      if (entities.back == null) {
        setUserState(message, 'bot_query_back');
        reply.push([queries.back]);
      } else {
        setUserState(message, 'idle');
      }
      return reply.join("\n");
    }
  };

}).call(this);
