// Generated by CoffeeScript 1.10.0
(function() {
  exports.replies = {
    intents: {
      unknown: "Sorry, didn't quite get that. Could you please rephrase that?",
      set_self_status: "Ok, got it!"
    }
  };

  exports.queries = {
    back: "When do you expect to be back?"
  };

}).call(this);
