// Generated by CoffeeScript 1.10.0
(function() {
  var Database, Rx, Slack, Wit, getUserState, log, processBundle;

  Rx = require('rx');

  Slack = require('./services/slack');

  Wit = require('./services/wit');

  Database = require('./services/database');

  log = require('./misc/util').log;

  getUserState = require('./services/database').getUserState;

  processBundle = require('./internal/process').processBundle;


  /* STREAMS */

  Slack.incoming.message$.subscribe((function(_this) {
    return function(message) {
      return getUserState(message).then(function(state) {
        return Wit.processMessage(message, state);
      });
    };
  })(this));

  Wit.bundle$.subscribe(function(bundle) {
    return processBundle(bundle).then((function(_this) {
      return function(bundle) {
        return Slack.send(bundle);
      };
    })(this));
  });

}).call(this);
