// Generated by CoffeeScript 1.10.0
(function() {
  exports.log = function(a) {
    return console.log(a);
  };

  exports.logResponse = function(err, response) {
    if (err != null) {
      return console.error(err);
    } else {
      return console.log(response);
    }
  };

}).call(this);
